language: php

php:
  - 5.3
  - 5.4
  - 5.5

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev

script: bin/phpunit -c app --coverage-text

after_script:
  - vendor/bin/phpcs -v --report=summary --standard=PSR1,PSR2 src
  - vendor/bin/phpmd src text codesize,unusedcode,design
  - vendor/bin/phpmd tests text codesize,unusedcode,design

