language: php

php:
  - 5.4
  - 5.5

env:
  - DOCTRINE_VERSION=2.2.*
  - DOCTRINE_VERSION=2.3.*
  - DOCTRINE_VERSION=2.4.*

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar require symfony/validator:${DOCTRINE_VERSION} --no-update
  - php composer.phar install --prefer-source --dev

script:
  - vendor/bin/phpunit --coverage-text

after_script:
  - vendor/bin/phpcs -v --report=summary --standard=PSR1,PSR2 src/ tests/
  - vendor/bin/phpmd src/,tests/ text codesize,unusedcode,design
  - vendor/bin/coveralls
